version: '3.4'

services:
  postgresql:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - api_network
volumes:
  postgresql:
networks:
  api_network:
    driver: bridge
